### ISSUE TITLE
[ not an issue ] code complexity

### ISSUE THREAD

**Issue by shahmilav** [leadweedy/Firefox-Proton-Square#10]
Out of curiosity:
The code seems very complex, especially the `userChrome.css` file. What would be the difference from this, compared to

```css
* {
   border-radius: 0px !important; 
}
```

which gives you
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/53659750/169178372-53a6c76f-c3ed-4a67-97c7-2df94844e3d4.png">
 with square corners everywhere?

The current way also has the issue that if Firefox introduces a new UI element the code needs to be updated.

**Comment by leadweedy** [comment]
The main thing gripe i have is not all UI elements should be squared. basically the question of whitelist vs blacklist. Current method does need to be updated, but is also less prone to unintended UI breakages. pros and cons to both methods.

With `* {border-radius: 0px !important;}` there would have to be a bunch of exceptions for the things that shouldnt be squared. This is especially true in userContent.css, which styles certain things on webpages. in userChrome, the first ones that come to mind are the download button, middle click scroll, and the firefox account profile picture, though im sure theres more its not been throughly tested. would still have to be occasionally updated in the case of breakages, tho perhaps less frequently.

In addition, `* {border-radius: 0px !important;}` does not affect pseudo-elements such as `::before` or `::after` in toggle buttons and such, so it cant replace everything.

example of running just `* {border-radius: 0px !important;}`. note the toggle button 
![image](https://user-images.githubusercontent.com/72583854/169473951-db7345de-15e6-4407-84d4-6ab84aa56a02.png)

More than half of userChrome are for other customization options (accent color and such). I only count 57 instances of explicit calls to `border-radius`, which i wouldnt consider to be too complex, though you can feel free to argue otherwise.
