### ISSUE TITLE
Extension Icons appear "pushed down", not centered

### ISSUE THREAD

**Issue by EktoHunter** [leadweedy/Firefox-Proton-Square#2]
I really love this theme, though when using it icons of extension appear "pushed down", is there a way for me to fix this?
![grafik](https://user-images.githubusercontent.com/23218251/142784680-9f44e291-8254-455c-9b7a-865c33d6675f.png)

**Comment by EktoHunter** [comment]
This might be intentional by leadweedy, but if anyone else needs the "fix" for this, I got some help on reddit:

SOLUTIONS:
After checking out the tool to inspect the browser UI I found out that the icons, as /u/It_Was_The_Other_Guy had suggested were too big / the navbar was too small. The icons are 40px tall, the navbar was set to 35. There are two possible fixes to this:
1. Enable Compact Mode by setting browser.compactmode.show in about:config to true, and then enabling compact mode from the toolbar customization screen. (credit to /u/It_Was_The_Other_Guy).
2. For the theme that I was using specifically, change #nav-bar to {height: 40px !important}.

Thanks for the help!

**Comment by leadweedy** [comment]
I am so sorry I never got to this, turns out I'm not notified of issues by default :/

It was not an intentional decision, but this was an ongoing issue that I'd been dealing with and ultimately decided to abandon trying to fix it in v1.5.0 by removing the code entirely. The navbar is now back to its default height of 40px and icons should appear centered again. 

I took a quick look at your code and I'd recommend removing `#search-container {height: 35px !important; padding-top: 0!important;}`. It would cause the searchbox to be uncentered now that the navbar is fixed.
![image](https://user-images.githubusercontent.com/72583854/145399515-59ec9241-3716-4180-b5a0-868f115c561f.png)

**Comment by leadweedy** [comment]
> Hey, thanks very much for the fix, and thanks for checking out the other tweaks that I put into my edit of your theme. Since you pretty much integrated all of the tweaks that I made into the original branch, I've archived my forked branch.
> 
> One last thing that I'm trying to do is creating an option in `about:config` as you did with the option to re-enable the round synch-pfp, just instead of a boolean I wanna enter a float that scales the pfp to a larger size as it looks quite small compared to the other icons.

I appreciate the feedback! I'll move the rest of this discussion to a new issue for organization
